config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :killed_monsters, only: :create
  resources :collected_coins, only: :create
  resources :deaths, only: :create
  resources :trophies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collected_coin.rb
# frozen_string_literal: true

class CollectedCoin < ApplicationRecord
  belongs_to :user
end

app/models/death.rb
class Death < ApplicationRecord
end

app/models/killed_monster.rb
# frozen_string_literal: true

class KilledMonster < ApplicationRecord
  belongs_to :monster
  belongs_to :user
end

app/models/monster.rb
class Monster < ApplicationRecord
  enum name: %i[turtle bowser]
  has_many :killed_monsters
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :killed_monsters
  has_many :deaths
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collected_coins_controller.rb
# frozen_string_literal: true

class CollectedCoinsController < ApplicationController
  def create
    CollectedCoin.create(
      user_id: params[:user_id],
      value: 10
    )
    redirect_to root_path(user_id: params[:user_id])
  end
end

app/controllers/deaths_controller.rb
# frozen_string_literal: true

class DeathsController < ApplicationController
  def create
    Death.create(user_id: params[:user_id])
    redirect_to root_path(user_id: params[:user_id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :create_user, only: :index
  before_action :create_monster, only: :index

  def index
    @coin = rand(2)
  end

  private

  def create_user
    @user = params[:user_id].present? ? User.find(params[:user_id]) : User.create
  end

  def create_monster
    if Monster&.last == KilledMonster&.last&.monster
      number = rand(2).zero?
      @monster = Monster.create(name: number ? :turtle : :bowser)
    else
      @monster = Monster.last
    end
  end
end

app/controllers/killed_monsters_controller.rb
# frozen_string_literal: true

class KilledMonstersController < ApplicationController
  def create
    KilledMonster.create(
      user_id: params[:user_id],
      monster: Monster.last
    )
    redirect_to root_path(user_id: params[:user_id])
  end
end

app/controllers/trophies_controller.rb
# frozen_string_literal: true

class TrophiesController < ApplicationController
  def index
    @user = params[:user_id]
    @trophies = TrophiesCountService.execute(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= form_with url: killed_monsters_path(user_id: @user), id: :killed_monsters_form do |f| %>
  <%= f.text_field :turtle, class: :turtle if @monster.turtle? %>
  <%= f.text_field :bowser, class: :bowser if @monster.bowser? %>
<% end %>
<%= form_with url: collected_coins_path(user_id: @user), id: :collected_coins_form do |f| %>
  <%= f.text_field :coin, class: :coin if !@coin.zero? %>
<% end %>
<%= form_with url: deaths_path(user_id: @user), id: :deaths_form do |f| %>
  <div class="bart"></div>
<% end %>
<%= link_to '', trophies_path(user_id: @user), class: :trophies %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShooterGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%="#{controller._prefixes.first}_#{action_name}"%>'>
    <%= yield %>
  </body>
</html>

app/views/trophies/index.html.erb
<p><%= @trophies[:coins] %> trófeu(s) de moedas coletadas</p>
<p><%= @trophies[:deaths] %> trófeu(s) de morte</p>
<p><%= @trophies[:turtles] %> trófeu(s) de abates de tartarugas</p>
<p><%= @trophies[:bowsers] %> trófeu(s) de abates de bowsers</p>
<%= link_to :voltar, root_path(user_id: @user) %>